goa_students = []
goa_students.append("andria")
goa_students.append("merabi")
goa_students.append("mate")
goa_students.append("gio gvardzela")
goa_students.append("aleqsandre")
goa_students.append("tobi")
goa_students.append("tazo")
goa_students.append("lazare")
goa_students.append("batoni gabriel molodini")
goa_students.append("irakli")
goa_students.append("mariam")
print(goa_students[0])
print(goa_students[1])
print(goa_students[2])
print(goa_students[3])
print(goa_students[4])
print(goa_students[5])
print(goa_students[6])
print(goa_students[7])
print(goa_students[8])
print(goa_students[9])
print(goa_students[10])
print(goa_students[11])

# GOA best ❤️
